apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx-privileged-disallowed
spec:
  containers:
  - image: perrea/nginx
    name: nginx
    securityContext:
      privileged: true
   